### ISSUE TITLE
OWASP config does not need copyright verbage

### ISSUE THREAD

**Issue by rljohnsn** [8x8Cloud/fiql-elasticsearch#2]
https://github.com/8x8Cloud/fiql-elasticsearch/blob/ff8e626d30493824d7346ac1524b4c34d2c297b2/build/owasp-scan-suppression.xml#L3

**Comment by kog** [comment]
@rljohnsn - yeah, I'd set those up in IDEA and they sorta came along for the ride. Thinking about it though it's probably just best to remove the notices. I'll be doing most of the maintenance as a free agent anyway...
